import {
  Home,
  CalendarDays,
  ClipboardList,
  Bell,
  BarChart3,
  CalendarCheck,
  Settings,
  RefreshCw,
  LogOut,
  User,
  ShieldAlert,
  Save,
  CheckCircle,
  Clock,
  Info,
  Calendar,
  MapPin,
  FileText,
  AlertTriangle,
  Send,
  Trash2,
  Edit2,
  X,
  Plus,
  ArrowRight,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Menu,
  MoreVertical,
  Activity,
  Users
} from 'lucide-react';

export const APP_ICONS = {
  dashboard: Home,
  roster: CalendarDays,
  requests: ClipboardList,
  updates: Bell,
  analytics: BarChart3,
  phTracker: CalendarCheck,
  admin: Settings,
  settings: Settings,
  refresh: RefreshCw,
  logout: LogOut,
  user: User,
  adminBadge: ShieldAlert,
  save: Save,
  check: CheckCircle,
  clock: Clock,
  info: Info,
  calendar: Calendar,
  location: MapPin,
  document: FileText,
  warning: AlertTriangle,
  send: Send,
  delete: Trash2,
  edit: Edit2,
  close: X,
  add: Plus,
  arrowRight: ArrowRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  menu: Menu,
  moreOptions: MoreVertical,
  activity: Activity,
  team: Users
};
