import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';import vm from 'node:vm';
import compatibility from '../../src/features/roster/compatibility.js';import guidance from '../../src/features/roster/guidance.js';
import {harness,currentSource,digest} from '../phase1/apps-script-harness.mjs';
function setup(options={}){const h=harness(currentSource,{activeEmail:'admin@example.invalid',adminEmail:'admin@example.invalid',...options});h.context.SpreadsheetApp.flush=()=>{};
 h.grids.Settings.push(['weekly_off_guidance_enabled','true'],['roster_v2_write_enabled','true'],['write_queue_v2_enabled','true']);
 const schemas=vm.runInContext('ROSTER_DRAFT_SCHEMAS',h.context);for(const [name,headers]of Object.entries(schemas))h.grids[name]=[[...headers]];
 h.grids.OffPolicies=[[...guidance.OFF_POLICY_HEADERS]];return h;}
function operation({revision=0,code='A',date='2030-01-07',...changes}={}){const op={operationId:crypto.randomUUID(),clientId:crypto.randomUUID(),tabId:crypto.randomUUID(),operationType:'OFF_POLICY_UPSERT',entityKey:'off-policies',expectedRevision:revision,
 payload:{policyId:crypto.randomUUID(),policyCode:code,effectiveMonday:date,reason:'Synthetic policy'},...changes};op.payloadHash=digest(compatibility.canonicalJson(guidance.policyOperation(op)));return op;}
const save=(h,op)=>h.post({action:'rosterv2offpolicy',...op}),read=h=>h.get('rosterv2offpolicies'),status=(h,op)=>h.get('rosterv2operation',{operationId:op.operationId}),recover=(h,op)=>h.post({action:'rosterv2offpolicyrecover',operationId:op.operationId});
function fault(h,index,after=false){const draft=h.context.rosterDraftWriteRow_,policy=h.context.rosterGuidanceWriteRow_;let n=0;
 const wrap=original=>function(...args){if(++n===index){if(after)original(...args);throw Error('Injected');}return original(...args);};
 h.context.rosterDraftWriteRow_=wrap(draft);h.context.rosterGuidanceWriteRow_=wrap(policy);
 return()=>{h.context.rosterDraftWriteRow_=draft;h.context.rosterGuidanceWriteRow_=policy;};}

test('policy write uses the shared journal, revision, verified actor and replay contract',()=>{const h=setup(),op=operation(),first=save(h,op);assert.equal(first.status,'CONFIRMED');for(let i=0;i<3;i++)assert.deepEqual(save(h,op),first);assert.equal(read(h).revision,1);assert.equal(read(h).policies[0].PolicyCode,'A');assert.equal(h.grids.OffPolicies[1][4],guidance.policyRuleJson('A'));assert.equal(h.grids.OffPolicies[1][10],'admin@example.invalid');assert.equal(h.grids.OperationLog.length,2);assert.equal(h.grids.OffPolicies.length,2);});
test('same operation ID with changed policy meaning is rejected',()=>{const h=setup(),op=operation();save(h,op);const changed=structuredClone(op);changed.payload.policyCode='B';changed.payloadHash=digest(compatibility.canonicalJson(guidance.policyOperation(changed)));assert.equal(save(h,changed).error.code,'IDEMPOTENCY_MISMATCH');assert.equal(read(h).revision,1);});
test('stale policy revision and duplicate effective Monday never append',()=>{const h=setup(),a=operation();save(h,a);assert.equal(save(h,operation()).error.code,'REVISION_CONFLICT');const duplicate=operation({revision:1});duplicate.payload.effectiveMonday=a.payload.effectiveMonday;duplicate.payloadHash=digest(compatibility.canonicalJson(guidance.policyOperation(duplicate)));assert.equal(save(h,duplicate).error.code,'VALIDATION_FAILED');assert.equal(h.grids.OffPolicies.length,2);});
test('invalid midweek, policy code, fields and identity are validation failures',()=>{for(const change of [op=>op.payload.effectiveMonday='2030-01-08',op=>op.payload.policyCode='C',op=>op.payload.extra=true,op=>op.operationId='bad']){const h=setup(),op=operation();change(op);assert.equal(save(h,op).error.code,'VALIDATION_FAILED');assert.equal(h.writes.length,0);}});
test('authorization and all required switches fail closed for direct calls',()=>{for(const key of ['weekly_off_guidance_enabled','roster_v2_write_enabled','write_queue_v2_enabled']){const h=setup();h.grids.Settings=h.grids.Settings.filter(row=>row[0]!==key);assert.equal(save(h,operation()).error.code,'FEATURE_DISABLED');assert.equal(h.writes.length,0);}const h=setup({activeEmail:''});assert.equal(save(h,operation()).error.code,'AUTHORIZATION_REQUIRED');assert.equal(read(h).error.code,'AUTHORIZATION_REQUIRED');assert.equal(h.writes.length,0);});
test('policy write rechecks switches after acquiring the lock',()=>{const h=setup(),get=h.context.LockService.getScriptLock;h.context.LockService.getScriptLock=()=>{const lock=get(),wait=lock.waitLock;lock.waitLock=ms=>{wait(ms);h.grids.Settings=h.grids.Settings.filter(row=>row[0]!=='weekly_off_guidance_enabled');};return lock;};assert.equal(save(h,operation()).error.code,'FEATURE_DISABLED');assert.equal(h.writes.length,0);assert.deepEqual(h.locks,['acquire','release']);});
for(const [index,after]of [[1,false],[1,true],[2,false],[2,true],[3,false],[3,true]])test(`policy partial write ${index} after=${after} is hidden until recovered`,()=>{const h=setup(),op=operation(),restore=fault(h,index,after);assert.equal(save(h,op).error.code,'RECOVERY_REQUIRED');restore();const before=read(h);assert.equal(before.revision,index===3&&after?1:0);const state=status(h,op);if(state.status==='NOT_FOUND')assert.equal(save(h,op).status,'CONFIRMED');else assert.ok(['FAILED','CONFIRMED'].includes(recover(h,op).status));assert.ok(h.grids.OffPolicies.length<=2);});
test('duplicate or corrupt policy evidence remains recovery required and invisible',()=>{for(const kind of ['duplicate','midweek']){const h=setup(),op=operation(),restore=fault(h,3);save(h,op);restore();if(kind==='duplicate')h.grids.OffPolicies.push([...h.grids.OffPolicies[1]]);else h.grids.OffPolicies[1][2]='2030-01-08';assert.equal(recover(h,op).status,'RECOVERY_REQUIRED');assert.equal(read(h).revision,0);assert.equal(recover(h,op).status,'RECOVERY_REQUIRED');}});
test('recovery validates rule, activation and audit evidence before confirmation',()=>{for(const [column,value]of [[4,'{}'],[5,false],[9,''],[10,'']]){const h=setup(),op=operation(),restore=fault(h,3);save(h,op);restore();h.grids.OffPolicies[1][column]=value;assert.equal(recover(h,op).status,'RECOVERY_REQUIRED');assert.equal(h.grids.OperationLog[1][8],'RECOVERY_REQUIRED');assert.equal(read(h).revision,0);}});
test('read/schema endpoints are advisory, explicit, private and make no writes',()=>{const h=setup(),before=h.writes.length,schema=h.get('rosterv2guidanceschema');assert.equal(schema.advisoryOnly,true);assert.equal(schema.automaticRosterChanges,false);assert.deepEqual(schema.headers,guidance.OFF_POLICY_HEADERS);assert.equal(read(h).revision,0);assert.equal(h.writes.length,before);});
test('missing OffPolicies is not created and legacy APIs remain unchanged',()=>{const h=setup();delete h.grids.OffPolicies;assert.equal(read(h).error.code,'ENTITY_NOT_FOUND');assert.equal(save(h,operation()).error.code,'ENTITY_NOT_FOUND');assert.equal(h.grids.OffPolicies,undefined);assert.ok(Array.isArray(h.get('masterroster')));});
test('policy confirmation never mutates MasterRoster or draft patches',()=>{const h=setup(),roster=JSON.stringify(h.grids.MasterRoster),draft=JSON.stringify(h.grids.RosterDraftPatches);save(h,operation());assert.equal(JSON.stringify(h.grids.MasterRoster),roster);assert.equal(JSON.stringify(h.grids.RosterDraftPatches),draft);});
